### ISSUE TITLE
App freezes on open

### ISSUE THREAD

**Issue by MacStache** [KevinCFechtel/FluxNews#38] opened 2024-04-11 07:39 UTC
Ran into an app breaking issue where the app works fine in the first time setup and usage, but freezes on startup when getting back to it. Requires a period of several hours of not using to reproduce. 

Freezes to a screen with just the logo displayed in the middle with the back and home buttons not working. Only the app switch button works. (As per screenshot).

Only way to fix the freezing is to delete data and do the first time setup again. Sorry, don't know how to explain it with more technicality.

Phone: Google Pixel 7 Pro

![Screenshot_20240411-102901](https://github.com/KevinCFechtel/FluxNews/assets/123492715/35cd09e4-8441-4bc0-a7a9-4b938b7bce73)

**Comment by KevinCFechtel** [comment] 2024-04-11 07:56
Hello, have you activated the sync on start?
If so, could you please try leaving sync on start deactivated and then reproduce the error again? 
This won't fix the error, but it will help me to find the error better 😊
I suspect it's basically the same problem as here https://github.com/KevinCFechtel/FluxNews/issues/29

**Comment by MacStache** [comment] 2024-04-11 14:08
I tried it with the setting both off and on. The issue persists on both. I can reproduce it by closing the app (not force closing but swiping it off from the app switcher menu). Every time I re open the app it hangs and I need to clear storage and paste in the api settings again. I have not touched any of the default settings and it happens everytime.

I don't think I can get you any debug logs either since I can't get into the export option. Tricky, this one.

**Comment by MacStache** [comment] 2024-04-11 14:31
Here's a logcat I managed to get with adb. I removed most of the not fluxnews related info from it so it's easier to go through. Hope this helps to narrow it down.

logcat.txt](https://github.com/KevinCFechtel/FluxNews/files/14947496/logcat.txt)

**Comment by KevinCFechtel** [comment] 2024-04-11 14:42
Super! Thank you very much, I think I already have an idea of what exactly the problem is here.
The version of the Miniflux server is being returned differently than the one I have. 
I'll take a look at this and create a bug fix. 
Did you download the app via F-Droid or via the Playstore?
If it was downloaded via the Playstore, I could send you the app as a beta tester, then we could speed up the troubleshooting process.

**Comment by KevinCFechtel** [comment] 2024-04-11 14:47
Yes, you can mail it to me: kevin@kevincfechtel.dev

**Comment by MacStache** [comment] 2024-04-11 18:29
I don't see it yet but will keep checking every now and then. Thanks for adressing this so swiftly.

**Comment by MacStache** [comment] 2024-04-13 15:20
I still don't see the beta anywhere. No updates available. Are you sure you entered me into the beta?

**Comment by KevinCFechtel** [comment] 2024-04-13 15:54
Hi, did you explicitly search for the app? 
The beta updates do not appear in the normal update overview for normal apps. 
You have to search for Flux News and then go to the description of the app, then it should say that you are participating in the beta program and that an update is available. 
Alternatively, try the following link:
https://play.google.com/apps/internaltest/4699713993175644776

**Comment by MacStache** [comment] 2024-04-13 16:03
I went through my profile and "manage apps" and browsed for the app that way and also tried searching the app from the playstore, but got no mention of the beta anywhere. The link you provided did the trick though.

I tested the beta and the freezing issue seems to be resolved. I tried closing and reopening the app several times and it works great! Just for the heck of it I also tested with the "auto refresh on startup" option on and that works too. It's a slower startup for sure, but that's to be expected as the refresh takes place then.

I think it's safe to say we can close this issue!

**Closed** 2024-04-13 16:08 UTC

**Comment by garret** [comment] 2024-11-03 09:31
When sync on startup is enabled I can see that screen for around 20 sec. Is it an expected behavior? 

Testing on Pixel 6

**Comment by MacStache** [comment] 2024-11-03 09:41
I would say yes, since it refreshes all your RSS sources on startup. If there are a lot of them it can take a while. 20 sec sounds a bit long though. For me a typical refresh takes about 5 seconds. Given that I don't have a huge amound of sources.

**Comment by KevinCFechtel** [comment] 2024-11-03 09:55
If a normal sync also takes about 20 seconds for you, then this is normal behavior. The splash screen is not deactivated during a sync on start until the new news has been loaded from the server and the list has been updated. 
The idea behind this was that after starting the app, the news list with new news is immediately available and there is not displayed an old News list for a few seconds before being updated again due to the sync.
